### ISSUE TITLE
Why is the first column in StudentExample.csv all filled with A?

### ISSUE THREAD

**Issue by indianquant** [abichown/SPA-Code#4]

**Comment by chriscook18** [comment]
This is a side effect of creating the CSV files in Excel.

The StudentExample file is of the following format:

> Each column represents a pair of students, and each row a project. Values of 1 to 4 should be filled in, representing the pairs preference. If the pair have not picked a project, leave that cell empty

There needs to be as many rows as there are projects in the CSV file. However, if the first or last project has not been picked by any pairs, the row in the Excel worksheet will be blank. When you save the Excel worksheet as a CSV file, it will cut off the empty top or bottom rows, leading to a CSV file with the incorrect number of rows - which will cause errors while running the program.

So, one way to ensure that Excel puts the empty rows into the CSV is to have a column that is always filled in. The letter "A" is used here since the character is not used for other purposes in the program.

There are two examples of this being necessary 
1) [StudentExample.csv](../blob/master/StudentExample.csv), as you mentioned - where project 1 was not selected by any students.
2) [Dataset 3](../blob/master/Dataset3CSV.csv), where project 67 (the last one) was not selected by any students.
